# Docker Compose for testing ECR images locally
# This pulls the images from your private ECR and runs them locally

version: '3.8'

services:
  api:
    image: ${ECR_REGISTRY}/house-price-api:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - house-price-network

  ui:
    image: ${ECR_REGISTRY}/house-price-ui:latest
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      api:
        condition: service_healthy
    networks:
      - house-price-network

networks:
  house-price-network:
    driver: bridge