model:
  best_model: LinearRegression
  feature_sets:
    rfe:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '9'
    - '10'
    - '13'
    - '14'
  mae: 8609.576310415061
  name: house_price_model
  parameters:
    copy_X: true
    fit_intercept: true
    n_jobs: null
    positive: false
  r2_score: 0.9901413701294144
  target_variable: price
